### ISSUE TITLE
GPIO implementation

### ISSUE THREAD

**Issue by zap8600** [jcmvbkbc/linux-xtensa#11]
What would it take for a GPIO driver to be made? I can't find the code @ESP32DE made in the original issue so I'm creating a new issue for this.

**Comment by jcmvbkbc** [comment]
> I can't find the code

I believe there was no kernel code, but a userspace program that was writing registers directly.

**Comment by zap8600** [comment]
> I believe there was no kernel code, but a userspace program that was writing registers directly.

Do you still have the program?

**Comment by jcmvbkbc** [comment]
> Do you still have the program?

It's `devmem`, part of busybox. See https://olimex.wordpress.com/2023/06/27/running-linux-with-kernel-6-3-on-open-source-hardware-board-with-esp32-s3/ for the use example.

**Comment by zap8600** [comment]
> It's `devmem`, part of busybox. See https://olimex.wordpress.com/2023/06/27/running-linux-with-kernel-6-3-on-open-source-hardware-board-with-esp32-s3/ for the use example.

What about in C code? I plan on trying to write a driver if I can figure out how.

**Comment by jcmvbkbc** [comment]
> What about in C code?

Depends on how fancy/portable you want your code. You can just write data directly to the desired physical address from the userspace if you don't care at all.

> I plan on trying to write a driver

Then it might be a good idea to take a look at other similar drivers.

**Comment by zap8600** [comment]
> Then it might be a good idea to take a look at other similar drivers.

Are there any similar drivers?

**Comment by jcmvbkbc** [comment]
A [whole bunch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/gpio?h=v6.5).

**Comment by zap8600** [comment]
Could we use [the MMIO GPIO driver](https://github.com/jcmvbkbc/linux-xtensa/blob/master/drivers/gpio/gpio-mmio.c)?

**Comment by jcmvbkbc** [comment]
IDK. Perhaps. Try and see?

**Comment by zap8600** [comment]
What is the minimum for writing my own driver?

**Comment by jcmvbkbc** [comment]
> What is the minimum for writing my own driver?

Minimum what? Minimum understanding: understanding the gpio driver structure and understanding the hardware.

**Comment by zap8600** [comment]
> Minimum what? Minimum understanding: understanding the gpio driver structure and understanding the hardware.

Minimum my driver needs to provide.

**Comment by jcmvbkbc** [comment]
IDK. I don't have any experience with the gpio subsystem whatsoever.

**Comment by zap8600** [comment]
Tell me if I'm wrong, but each GPIO pin takes up 2 bytes in the MMIO, so GPIO0 is at `0x60004000`, GPIO1 is at `0x60004004`, etc. Is this right?

**Comment by jcmvbkbc** [comment]
> Is this right?

No. Take a look at the chapter 6.14 "Register Summary" in the [esp32s3 TRM](https://www.espressif.com/sites/default/files/documentation/esp32-s3_technical_reference_manual_en.pdf) for the details.

**Comment by zap8600** [comment]
Tell me if I'm wrong, but would this work?
```c
#include <stdint.h>

// Define base address of GPIO matrix
#define GPIO_MATRIX_BASE 0x60004000

// Define GPIO matrix registers (offsets from base address)
#define GPIO_MATRIX_IN_CTRL 0x0
#define GPIO_MATRIX_OUT_CTRL 0x4
// ... Add more register offsets as needed

int main() {
    // Pointer to the GPIO matrix base address
    volatile uint32_t* gpio_matrix_ptr = (volatile uint32_t*)GPIO_MATRIX_BASE;

    // Example: Configure GPIO21 as an input from a specific source
    gpio_matrix_ptr[GPIO_MATRIX_IN_CTRL / 4] &= ~(0x1F << 10); // Clear bits 14-10
    gpio_matrix_ptr[GPIO_MATRIX_IN_CTRL / 4] |= (0x01 << 10);  // Set bits 14-10 to the source you want

    // Example: Configure GPIO22 as an output to a specific destination
    gpio_matrix_ptr[GPIO_MATRIX_OUT_CTRL / 4] &= ~(0x1F << 10); // Clear bits 14-10
    gpio_matrix_ptr[GPIO_MATRIX_OUT_CTRL / 4] |= (0x02 << 10);  // Set bits 14-10 to the destination you want

    // Add more configurations as needed...

    // Now GPIO21 and GPIO22 are configured according to your settings.

    // Add your main code here...

    return 0;
}
```

**Comment by jcmvbkbc** [comment]
> would this work?

About that pattern: tell me if I'm wrong, but you can compile it, run it and see for yourself?

I mean, the human capacity is limited, it makes sense to ask humans the questions that the hardware cannot answer.

**Comment by zap8600** [comment]
So I did a bit of thinking, and I think I know how to use the GPIO now. I can use GPIO_ENABLE_REG to set the pin I want to output, then pull it high with GPIO_OUT_REG. I'm not sure when I'll be able to test my code, but I'm (sorta) confident in my code.
