### ISSUE TITLE
SD/MMC host controller

### ISSUE THREAD

**Issue by Matthias199** [jcmvbkbc/linux-xtensa#16]
Did somebody use it ? or try to use it ?

**Comment by jcmvbkbc** [comment]
No, AFAIK. I've used SD card in SPI mode, it works and shows read speed of ~300KByte/s.

**Comment by Matthias199** [comment]
yes I read in the wiki taht it was working :) But I plan to use SPI for something else,
I just wanted to no if there was a special reason or lack of use for you.
If the last one I will dive in to it if my PCBs are ready

**Comment by jcmvbkbc** [comment]
> I just wanted to no if there was a special reason or lack of use for you.

No special reason, just haven't had a chance.
