### ISSUE TITLE
OpenCL support

### ISSUE THREAD

**Issue by guglovich** [jcmvbkbc/linux-xtensa#2]
I read that Xtensa HiFi 2 was used for AMD TrueAudio and there computing is sort of with OpenCL. Is Xtensa HiFi 2 an ASIC chip and is there compute support? In general, not just in OpenCL. And if so, will there be support in the OpenCL drivers?

Pocl replied that if a commit is sent to them, they can accept support in the project.

**Comment by jcmvbkbc** [comment]
@guglovich I'm not sure I understand your request.
This repository is for xtensa linux, i.e. linux running on xtensa cores.
I'm not aware of any open implementation of OpenCL for xtensa, but I know that Cadence/Tensilica has one.

**Comment by guglovich** [comment]
@jcmvbkbc  Here I have just the DSP HiFi EP from Tensilica, didn't know Xtensa was different, I thought you were referring to them. I'll be looking for their Git then. 
My goal is to somehow use this DSP, which doesn't show up among the devices in Linux and has no practical use.

**Comment by jcmvbkbc** [comment]
> I have just the DSP HiFi EP from Tensilica, didn't know Xtensa was different

Xtensa is the name of processor architecture, Cadence/Tensilica is the name of the company developing it.
